### PR TITLE
Made a landing page for arch 

### LINKED ISSUE #2: Change design
We need to add an Arch Linux design for the landing page. The design files should be placed in: `static/themes/archlinux`. Check out `static/themes/fedora` as example.

### PR DESCRIPTION
**Pull request by sonuishaq67**
Closes #2 
[x] Made a sample questions page (i.e) arch.yml
[x] Updated build.sh
[x] Updated Readme 
[x] added icons and logo 
[x] Also updated the fork to latest version of fedora-infra/asknot-ng

If there's anything to be changed please do inform and ill change it

### CODE REVIEW

**Comment by polyzen** [comment]
Please provide a merge request against the `archlinux` branch.

**Comment by sonuishaq67** [comment]
Oh okays

**Comment by sonuishaq67** [comment]
> Please provide a merge request against the `archlinux` branch.

Hey @polyzen it would be better if archlinux was the default branch for this repo right

**Comment by polyzen** [comment]
It would.

**Comment by sonuishaq67** [comment]
nice

**Pull request closed without merging**
